In [2]:
import pandas as pd

dogs = pd.read_csv('ShelterDogs.csv')
dogs.head()

,ID,name,age,sex,breed,date_found,adoptable_from,posted,color,coat,size,neutered,housebroken,likes_people,likes_children,get_along_males,get_along_females,get_along_cats,keep_in
0,23807,Gida,0.25,female,Unknown Mix,12/10/19,12/11/19,12/11/19,red,short,small,no,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,533,Frida És Ricsi,0.17,female,Unknown Mix,12/1/19,12/1/19,12/9/19,black and white,short,small,no,NaN,yes,yes,yes,yes,yes,NaN
2,23793,NaN,4.00,male,Unknown Mix,12/8/19,12/23/19,12/8/19,saddle back,short,medium,no,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,23795,NaN,1.00,male,Unknown Mix,12/8/19,12/23/19,12/8/19,yellow-brown,medium,medium,no,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,23806,Amy,2.00,female,French Bulldog Mix,12/10/19,12/11/19,12/11/19,black,short,small,no,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
dogs.describe()

                 ID          age
count   2937.000000  2937.000000
mean    1742.655431     8.569551
std     4023.313413     4.140216
min        1.000000     0.150000
25%      167.000000     5.830000
50%      556.000000     8.670000
75%     1451.000000    11.250000
max    23809.000000    21.920000

In [4]:
dogs.info(
)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2937 entries, 0 to 2936
Data columns (total 19 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   ID                 2937 non-null   int64
 1   name               2845 non-null   object
 2   age                2937 non-null   float64
 3   sex                2937 non-null   object
 4   breed              2937 non-null   object
 5   date_found         2937 non-null   object
 6   adoptable_from     2937 non-null   object
 7   posted             2937 non-null   object
 8   color              2937 non-null   object
 9   coat               2937 non-null   object
 10  size               2937 non-null   object
 11  neutered           1852 non-null   object
 12  housebroken        460 non-null    object
 13  likes_people       1999 non-null   object
 14  likes_children     1219 non-null   object
 15  get_along_males    1633 non-null   object
 16  get_along_females  1673 non-null   object
 17  get_along_cats     431 non-null    object
 18  keep_in            1916 non-null   object
dtypes: float64(1), int64(1), object(17)
memory usage: 436.1+ KB

### A dog's Coat

In [5]:
dogs['coat'] = dogs['coat'].astype('category')
dogs['coat'].value_counts(dropna=False)

coat
short         1972
medium         565
wirehaired     220
long           180
Name: count, dtype: int64

#### The .cat accessor object

### Setting Series categories

In [6]:
# Set categories:

dogs['coat'] = dogs['coat'].cat.set_categories(
    new_categories=['short', 'medium', 'long']
)

In [7]:
# Check value counts:
dogs['coat'].value_counts(dropna=False)

coat
short     1972
medium     565
NaN        220
long       180
Name: count, dtype: int64

In [8]:
# Setting Order
dogs['coat'] = dogs['coat'].cat.set_categories(
    new_categories=['short', 'medium', 'long'],
    ordered=True
)

dogs['coat'].head(3)

0    short
1    short
2    short
Name: coat, dtype: category
Categories (3, object): ['short' < 'medium' < 'long']

In [9]:
dogs['likes_people'].value_counts(dropna=False)

likes_people
yes    1991
NaN     938
no        8
Name: count, dtype: int64

A `NaN` could mean:
1. Truly unknown (we didn't check)
2. Not sure (dog likes 'some' people)

### Adding categories

In [10]:
dogs['likes_people'] = dogs['likes_people'].astype('category')
dogs['likes_people'] = dogs['likes_people'].cat.add_categories(
    new_categories=['did not check', 'could not tell']
)

In [11]:
# Check categories:
dogs['likes_people'].cat.categories

Index(['no', 'yes', 'did not check', 'could not tell'], dtype='object')

In [12]:
# New categories

dogs['likes_people'].value_counts(dropna=False)

likes_people
yes               1991
NaN                938
no                   8
did not check        0
could not tell       0
Name: count, dtype: int64

### Removing categories

In [13]:
dogs['coat'] = dogs['coat'].astype('category')
dogs["coat"] = dogs["coat"].cat.remove_categories(removals=["wirehaired"])

ValueError: removals must all be in old categories: {'wirehaired'}

In [ ]:
# Check the categories
dogs['coat'].cat.categories

Index(['short', 'medium', 'long'], dtype='object')

In [ ]:
# Check frequency counts while also printing the NaN count
print(dogs['keep_in'].value_counts(dropna=False))

keep_in
both flat and garden    1224
NaN                     1021
garden                   510
flat                     182
Name: count, dtype: int64

In [ ]:
# Switch to a categorical variable
dogs["keep_in"] = dogs["keep_in"].astype("category")

In [ ]:
dogs['keep_in'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 2937 entries, 0 to 2936
Series name: keep_in
Non-Null Count  Dtype
--------------  -----
1916 non-null   category
dtypes: category(1)
memory usage: 3.1 KB

In [ ]:

# Add new categories
new_categories = ["Unknown History", "Open Yard (Countryside)"]
dogs["keep_in"] = dogs["keep_in"].cat.add_categories(new_categories)

In [ ]:
# Check frequency counts one more time
print(dogs['keep_in'].cat.categories)

Index(['both flat and garden', 'flat', 'garden', 'Unknown History',
       'Open Yard (Countryside)'],
      dtype='object')

In [ ]:
# Check frequency counts one more time
print(dogs['keep_in'].value_counts(dropna=False))

keep_in
both flat and garden       1224
NaN                        1021
garden                      510
flat                        182
Unknown History               0
Open Yard (Countryside)       0
Name: count, dtype: int64

In [ ]:
# Set "maybe" to be "no"
dogs.loc[dogs["likes_children"] == "maybe", "likes_children"] = "no"

# Print out categories
print(dogs["likes_children"].cat.categories)

AttributeError: Can only use .cat accessor with a 'category' dtype

In [ ]:
 # Set "maybe" to be "no"
dogs.loc[dogs["likes_children"] == "maybe", "likes_children"] = "no"

In [ ]:
# Print the frequency table
print(dogs["likes_children"].value_counts(dropna=False))

likes_children
NaN    1718
yes    1172
no       47
Name: count, dtype: int64

In [ ]:
# Print the categories one more time
print(dogs['likes_children'].cat.categories)

AttributeError: Can only use .cat accessor with a 'category' dtype

### Updating categories

In [ ]:
# The breed variable
# Breed value counts:
dogs['breed'] = dogs['breed'].astype('category')
dogs['breed'].value_counts()

breed
Unknown Mix                                                       1524
German Shepherd Dog Mix                                            190
Dachshund Mix                                                      147
Labrador Retriever Mix                                              83
Staffordshire Terrier Mix                                           62
                                                                  ...
Tibetan Terrier                                                      1
American Bulldog Mix                                                 1
Alaskan Malamute, Caucasian Ovtcharka, German Shepherd Dog Mix       1
Akita, Labrador Retriever Mix                                        1
Akita, German Shepherd Dog Mix                                       1
Name: count, Length: 277, dtype: int64

## Renaming categories
The `rename_categories` method:

In [ ]:
Series.cat.rename_categories(new_categories=dict)

NameError: name 'Series' is not defined

In [ ]:
# Make a dictionary

my_changes = {'Unknown Mix': 'Unknown'}

In [ ]:
# Rename the category
dogs['breed'] = dogs['breed'].cat.rename_categories(my_changes)

In [ ]:
#Bread value counts:
dogs['breed'].value_counts()

breed
Unknown                                                           1524
German Shepherd Dog Mix                                            190
Dachshund Mix                                                      147
Labrador Retriever Mix                                              83
Staffordshire Terrier Mix                                           62
                                                                  ...
Tibetan Terrier                                                      1
American Bulldog Mix                                                 1
Alaskan Malamute, Caucasian Ovtcharka, German Shepherd Dog Mix       1
Akita, Labrador Retriever Mix                                        1
Akita, German Shepherd Dog Mix                                       1
Name: count, Length: 277, dtype: int64

### Renaming categories with a function

In [ ]:
# Update multiple categories:

dogs['sex'] = dogs['sex'].cat.categories(lambda c: c.title())

AttributeError: Can only use .cat accessor with a 'category' dtype

In [ ]:
dogs['sex'].cat.categories

AttributeError: Can only use .cat accessor with a 'category' dtype

## Common replacement issues

In [ ]:
# Does not work! "Unknown" already exists
use_new_categories = {'Unknown Mix': 'Unknown'}

### Collapsing categories setup

In [ ]:
dogs['color'] = dogs['color'].astype('category')
print(dogs['color'].cat.categories)

Index(['apricot', 'black', 'black and brown', 'black and tan',
       'black and white', 'brown', 'brown and white', 'dotted', 'golden',
       'gray', 'gray and black', 'gray and white', 'red', 'red and white',
       'sable', 'saddle back', 'spotty', 'striped', 'tricolor', 'white',
       'wild boar', 'yellow', 'yellow-brown'],
      dtype='object')

In [ ]:
# Create a dictionary and use `.replace`:

update_colors = {
    'black and brown': 'black',
    'black and tan': 'black',
    'black and white': 'black',
    }

In [ ]:
dogs['main_color'] = dogs['color'].replace(update_colors)

C:\Users\USER\AppData\Local\Temp\ipykernel_2532\1953001383.py:1: FutureWarning: The behavior of Series.replace (and DataFrame.replace) with CategoricalDtype is deprecated. In a future version, replace will only be used for cases that preserve the categories. To change the categories, use ser.cat.rename_categories instead.
  dogs['main_color'] = dogs['color'].replace(update_colors)

In [ ]:
# Check the series data type:
dogs['main_color'].dtype

CategoricalDtype(categories=['apricot', 'black', 'brown', 'brown and white', 'dotted',
                  'golden', 'gray', 'gray and black', 'gray and white', 'red',
                  'red and white', 'sable', 'saddle back', 'spotty', 'striped',
                  'tricolor', 'white', 'wild boar', 'yellow', 'yellow-brown'],
, ordered=False, categories_dtype=object)

In [ ]:
## Concert back to categorical
dogs['main_color'] = dogs['main_color'].astype('category')
dogs['main_color'].cat.categories

Index(['apricot', 'black', 'brown', 'brown and white', 'dotted', 'golden',
       'gray', 'gray and black', 'gray and white', 'red', 'red and white',
       'sable', 'saddle back', 'spotty', 'striped', 'tricolor', 'white',
       'wild boar', 'yellow', 'yellow-brown'],
      dtype='object')

In [ ]:
# Create the my_changes dictionary
my_changes = {'Maybe?': 'Maybe'}
# Rename the categories listed in the my_changes dictionary
dogs["likes_children"] = dogs['likes_children'].cat.rename_categories(my_changes)

# Use a lambda function to convert all categories to uppercase using upper()
dogs["likes_children"] =  dogs["likes_children"].cat.rename_categories(lambda c: c.upper())

# Print the list of categories
print(dogs['likes_children'].cat.categories)

AttributeError: Can only use .cat accessor with a 'category' dtype

In [ ]:
# Create the update_coats dictionary
update_coats = {'wirehaired': 'medium', 'medium-long': 'medium'}

# Create a new column, coat_collapsed
dogs["coat_collapsed"] = dogs['coat'].replace(update_coats)

# Convert the column to categorical
dogs['coat_collapsed']=dogs['coat_collapsed'].astype('category')

# Print the frequency table
print(dogs['coat_collapsed'].cat.categories)

Index(['short', 'medium', 'long'], dtype='object')

In [ ]:
print(dogs['coat_collapsed'].value_counts())

coat_collapsed
short     1972
medium     565
long       180
Name: count, dtype: int64

:

In [ ]:

# Print out the current categories of the size variable
print(dogs['size'].cat.categories)

AttributeError: Can only use .cat accessor with a 'category' dtype

In [ ]:
# Print out the current categories of the size variable
print(dogs["size"].cat.categories)

# Reorder the categories using the list provided
dogs["size"] = dogs['size'].cat.reorder_categories(
    new_categories = ['small', 'medium', 'large'],
    ordered=True
)

AttributeError: Can only use .cat accessor with a 'category' dtype

In [ ]:
# Print out the current categories of the size variable
print(dogs["size"].cat.categories)

# Reorder the categories, specifying the Series is ordinal, and overwriting the original series
dogs["size"].cat.reorder_categories(
  new_categories=["small", "medium", "large"],
  ordered=True,
  inplace=True
)

In [ ]:
# Previous code
dogs["size"].cat.reorder_categories(
  new_categories=["small", "medium", "large"],
  ordered=True,
  inplace=True
)

# How many Male/Female dogs are available of each size?
print(dogs.groupby('size')['sex'].value_counts())

# Do larger dogs need more room to roam?
print(dogs.groupby('size')['keep_in'].value_counts())

AttributeError: Can only use .cat accessor with a 'category' dtype

### Cleaning and Accessing data

In [16]:
dogs['get_along_cats'].value_counts()

get_along_cats
yes    275
no     156
Name: count, dtype: int64

In [17]:
# Removing whitespace: .strip()

dogs['get_along_cats'] = dogs['get_along_cats'].str.strip()

In [18]:
# Check the frequency counts:
dogs['get_along_cats'].value_counts()

get_along_cats
yes    275
no     156
Name: count, dtype: int64

### Fixing issues: capitalization

In [20]:
# Capitalization: .title(), .upper(), .lower()

dogs['get_along_cats'] = dogs['get_along_cats'].str.title()

In [21]:
# Check the frequency counts:
dogs['get_along_cats'].value_counts()

get_along_cats
Yes    275
No     156
Name: count, dtype: int64

### Fixing issues: misspelled word

In [22]:
# Fixing a typo with .replace()
replace_map = {'Noo':'No'}
dogs['get_along_cats'].replace(replace_map, inplace=True)

In [23]:
dogs['get_along_cats'].value_counts()

get_along_cats
Yes    275
No     156
Name: count, dtype: int64

### Checking data type

In [24]:
# Checking the dtype
dogs['get_along_cats'].dtype

dtype('O')

In [25]:
# Converting back to a category

dogs['get_along_cats'] = dogs['get_along_cats'].astype('category')

In [26]:
# Checking the dtype
dogs['get_along_cats'].dtype

CategoricalDtype(categories=['No', 'Yes'], ordered=False, categories_dtype=object)

# Using the str accessor object

In [27]:
# Searching for a string

dogs['breed'].str.contains('Shepherd', regex=False)

0       False
1       False
2       False
3       False
4       False
        ...
2932    False
2933    False
2934    False
2935    False
2936     True
Name: breed, Length: 2937, dtype: bool

### Accessing data with loc

In [28]:
# Acess Series values based on category

dogs.loc[dogs['get_along_cats'] == 'Yes', 'size']

1        small
6        small
9        small
13       small
16       small
         ...
2722    medium
2746    medium
2763    medium
2809     large
2815    medium
Name: size, Length: 275, dtype: object

In [34]:
# Series value counts:
dogs.loc[dogs['get_along_cats'] == 'Yes', 'size'].value_counts(sort=False)

size
small      69
medium    169
large      37
Name: count, dtype: int64

In [35]:
# Fix the misspelled word
replace_map = {"Malez": "male"}

# Update the sex column using the created map
dogs["sex"] = dogs["sex"].replace(replace_map)

In [36]:
print(dogs["sex"].value_counts())

sex
male      1681
female    1256
Name: count, dtype: int64

In [37]:
# Strip away leading whitespace
dogs["sex"] = dogs["sex"].str.strip()

In [38]:
print(dogs["sex"].value_counts())

sex
male      1681
female    1256
Name: count, dtype: int64

In [39]:
# Make all responses lowercase
dogs["sex"] = dogs['sex'].str.lower()

print(dogs["sex"].value_counts())

sex
male      1681
female    1256
Name: count, dtype: int64

In [40]:
# Convert to a categorical Series
dogs["sex"] =dogs['sex'].astype('category')

print(dogs["sex"].value_counts())

sex
male      1681
female    1256
Name: count, dtype: int64

In [41]:
# Find the count of male and female dogs who have a "long" coat
print(dogs.loc[dogs['coat'] == 'long', 'sex'].value_counts())

sex
male      124
female     56
Name: count, dtype: int64

In [42]:
# Print the mean age of dogs with a breed of "English Cocker Spaniel"
print(dogs.loc[dogs['breed'] == 'English Cocker Spaniel', 'age'].mean())

8.186153846153847

In [43]:
# Count the number of dogs that have "English" in their breed name
print(dogs[dogs["breed"].str.contains('English', regex=False)].shape[0])

35