### Simple string comparison

In [1]:
pip install thefuzz

Defaulting to user installation because normal site-packages is not writeable
Collecting thefuzz
  Downloading thefuzz-0.22.1-py3-none-any.whl.metadata (3.9 kB)
Requirement already satisfied: rapidfuzz<4.0.0,>=3.0.0 in c:\users\user\appdata\roaming\python\python313\site-packages (from thefuzz) (3.14.3)
Downloading thefuzz-0.22.1-py3-none-any.whl (8.2 kB)
Installing collected packages: thefuzz
Successfully installed thefuzz-0.22.1
Note: you may need to restart the kernel to use updated packages.

In [2]:
# Lets us compare between two strings
from thefuzz import fuzz

In [4]:
# Compare reading vs reading
fuzz.WRatio('Reeding', 'Reading')

86

### Partial strings different orderings

In [5]:
# Partial string comparison
fuzz.WRatio('Houston Rockets', 'Rockets')

90

In [7]:
# Partial string comparison with different order
fuzz.WRatio('Huston Rockets vsLos Angeles Lakers', 'Lakers vs Rockets')

86

### Comparison with arrays

In [8]:
# Import process
from thefuzz import process
import pandas as pd

# Define string and array of possible matches
string = "Houston Rockets vs Los Angeles Lakers"
choices = pd.Series(['Rockets vs Lakers', 'Lakers vs Rockets', 'Houson vs Los Angeles', 'Heat vs Bulls'])

process.extract(string, choices, limit=2)

[('Rockets vs Lakers', 86, 0), ('Lakers vs Rockets', 86, 1)]

In [10]:
survey = pd.read_csv('ride_sharing_new.csv')
survey.head()

,Unnamed: 0,duration,station_A_id,station_A_name,station_B_id,station_B_name,bike_id,user_type,user_birth_year,user_gender
0,0,12 minutes,81,Berry St at 4th St,323,Broadway at Kearny,5480,2,1959,Male
1,1,24 minutes,3,Powell St BART Station (Market St at 4th St),118,Eureka Valley Recreation Center,5193,2,1965,Male
2,2,8 minutes,67,San Francisco Caltrain Station 2 (Townsend St...,23,The Embarcadero at Steuart St,3652,3,1993,Male
3,3,4 minutes,16,Steuart St at Market St,28,The Embarcadero at Bryant St,1883,1,1979,Male
4,4,11 minutes,22,Howard St at Beale St,350,8th St at Brannan St,4626,2,1994,Male

In [11]:
categories

NameError: name 'categories' is not defined

### Collapsing all of the state

In [ ]:
# For each correct category
for state in categories['state']:
    # Fined potential matches in states with typoes
    matches = process.extract(state, survey['state'], limit=survey.shape[0])
    # For each potential match match
    for potential_match in matches:
        # If high similarity score
        if potential_match[1] >= 80:
            # Replace typo with correct category
            survey.loc[survey['state'] == potential_match[0], 'state']  == state

In [14]:
restaurants = pd.read_csv('restaurants_L2.csv')
restaurants.head()

,Unnamed: 0,name,addr,city,phone,type
0,0,arnie morton's of chicago,435 s. la cienega blv .,los angeles,3102461501,american
1,1,art's delicatessen,12224 ventura blvd.,studio city,8187621221,american
2,2,campanile,624 s. la brea ave.,los angeles,2139381447,american
3,3,fenix,8358 sunset blvd. west,hollywood,2138486677,american
4,4,grill on the alley,9560 dayton way,los angeles,3102760615,american

In [13]:
# Import process from thefuzz
from thefuzz import process

# Store the unique values of cuisine_type in unique_types
unique_types = restaurants['cuisine_type'].unique()

# Calculate similarity of 'asian' to all values of unique_types
print(process.extract('asian', unique_types,  limit = len(unique_types)))

# Calculate similarity of 'american' to all values of unique_types
print(process.extract('american', unique_types, limit= len(unique_types)))

# Calculate similarity of 'italian' to all values of unique_types
print(process.extract('italian', unique_types, limit=len(unique_types)))

KeyError: 'cuisine_type'

In [15]:
# Inspect the unique values of the cuisine_type column
print(restaurants['cuisine_type'].unique())

KeyError: 'cuisine_type'

In [ ]:
# Create a list of matches, comparing 'italian' with the cuisine_type column
matches = process.extract('italian', restaurants['cuisine_type'], limit=len(restaurants.cuisine_type))

# Inspect the first 5 matches
print(matches[0:5])

In [ ]:
# Create a list of matches, comparing 'italian' with the cuisine_type column
matches = process.extract('italian', restaurants['cuisine_type'], limit=len(restaurants.cuisine_type))

# Iterate through the list of matches to italian
for match in matches:
  # Check whether the similarity score is greater than or equal to 80
  if match[1] >= 80:
    # Select all rows where the cuisine_type is spelled this way, and set them to the correct cuisine
    restaurants.loc[restaurants['cuisine_type'] == match[0], 'cuisine_type'] = 'italian'

In [ ]:
# Iterate through categories
for cuisine in categories:  
  # Your previous code should be placed here
  # For example, create a list of matches
  matches = process.extract(cuisine, restaurants['cuisine_type'], limit=len(restaurants.cuisine_type))
  
  # Iterate through the list of matches
  for match in matches:
    # Check the similarity score
    if match[1] >= 80:
      # Update the cuisine_type
      restaurants.loc[restaurants['cuisine_type'] == match[0]] = cuisine
# Inspect the final result
print(restaurants['cuisine_type'].unique())